[package]
name = "egistec_eh575"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.8"
flume = "0.10.5"
lazy_static = "1.4.0"